### ISSUE TITLE
LXTerm 0.2.0 fails to properly display neovim

### ISSUE THREAD

**Issue by phansel** [lxde/lxterminal#72] opened 2019-06-16 15:16 UTC
LXTerm shows random characters that do not go away when neovim is run. Explanation of issue is here:

https://github.com/neovim/neovim/issues/10240

**Comment by egmontkob** [comment] 2019-06-17 07:35
LXTerminal can be compiled against GTK2 and in turn an 8 year old, no longer maintained VTE doing the terminal emulation; or GTK3 with a fresh VTE. The issue is only present with the old VTE, and won't be fixed. Use GTK3.

**Closed** 2019-07-01 18:36 UTC
